name: vui
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  avatar_glow: ^3.0.1
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  highlight_text: ^1.7.0
  speech_to_text: ^6.5.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
